project:
  type: website

website:
  title: "AAU-Math"
  description: "Offsite page for the Department of Mathematical Sciences at Aalborg University"
  open-graph: true
  navbar:
    background: "#211a52"
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: LSS.qmd
        text: Seminar Series
      - href: https://climateaau.github.io/
        text: Climate@AAU
      - href: https://climateaau.github.io/emcc-x
        text: EMCC 2026
      - text: Previous Events
        menu:
        - href: XV.qmd
          text: XV Math-Econ
        - href: LM-PhD.qmd
          text: PhD Course in Long Memory
        - href: LMS.qmd
          text: Long Memory Symposium
        - href: Resampling-PhD.qmd
          text: PhD Course in Resampling Techniques
#      - about.qmd
    tools:
      - icon: link-45deg
        href: https://www.math.aau.dk/
      #- icon: github
      #  href: https://github.com/Math-at-Aalborg-University
      - icon: linkedin
        href: https://www.linkedin.com/company/institut-for-matematiske-fag-aalborg-universitet/

format:
  html:
    theme: morph
    css: styles.css
#    fontsize: 1rem
#    toc: true



